# Generated by Django 5.1.6 on 2025-04-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('MaDM', models.AutoField(primary_key=True, serialize=False)),
                ('TenDM', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('MaNguoiDung', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=255)),
                ('SDT', models.CharField(max_length=15)),
                ('NgaySinh', models.DateField()),
                ('GioiTinh', models.CharField(max_length=10)),
                ('ChucVu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='The',
            fields=[
                ('MaThe', models.AutoField(primary_key=True, serialize=False)),
                ('TenThe', models.CharField(max_length=255)),
                ('Slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('MaBV', models.AutoField(primary_key=True, serialize=False)),
                ('TieuDe', models.CharField(max_length=255)),
                ('ThoiGianDang', models.DateTimeField()),
                ('NoiDung', models.TextField()),
                ('MaDM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.danhmuc')),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='LichDangBai',
            fields=[
                ('MaLDB', models.AutoField(primary_key=True, serialize=False)),
                ('ThoiGianDang', models.DateTimeField()),
                ('TrangThai', models.BooleanField()),
                ('MaBV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.baiviet')),
            ],
        ),
        migrations.CreateModel(
            name='DuyetBaiViet',
            fields=[
                ('MaDuyet', models.AutoField(primary_key=True, serialize=False)),
                ('NgayDuyet', models.DateTimeField()),
                ('TrangThai', models.BooleanField()),
                ('GhiChu', models.TextField()),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('MaTK', models.AutoField(primary_key=True, serialize=False)),
                ('TenDangNhap', models.CharField(max_length=255)),
                ('MatKhau', models.CharField(max_length=255)),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='BaiVietThe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaBV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.baiviet')),
                ('MaThe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.quanlythe')),
            ],
        ),
    ]
