# Generated by Django 5.1.6 on 2025-05-01 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('ma_bv', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=255)),
                ('trang_thai', models.CharField(max_length=100)),
                ('ngay_dang', models.DateField()),
                ('duong_dan', models.URLField()),
                ('tom_tat', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('anh', models.ImageField(blank=True, null=True, upload_to='images/bai_viet/')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='The',
            fields=[
                ('ma_the', models.AutoField(primary_key=True, serialize=False)),
                ('ten_the', models.CharField(max_length=255)),
                ('so_bai_viet', models.IntegerField()),
                ('slug', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaiVietLichDangBai',
            fields=[
                ('ma_ldb', models.AutoField(primary_key=True, serialize=False)),
                ('ma_bv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.baiviet')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('ma_dm', models.AutoField(primary_key=True, serialize=False)),
                ('ten_dm', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('so_bai_viet', models.IntegerField(default=0)),
                ('order_index', models.IntegerField()),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csdl.danhmuc')),
            ],
        ),
        migrations.AddField(
            model_name='baiviet',
            name='ma_dm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.danhmuc'),
        ),
        migrations.CreateModel(
            name='DuyetBaiViet',
            fields=[
                ('ma_duyet', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_duyet', models.DateField()),
                ('trang_thai', models.CharField(max_length=100)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ma_bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.baiviet')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LichDangBai',
            fields=[
                ('ma_ldb', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_dang', models.DateField()),
                ('do_uu_tien', models.BooleanField(default=False)),
                ('ngay_dong', models.DateField(blank=True, null=True)),
                ('ma_bv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.baiviet')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('ma_media', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('type_name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaiVietMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_bv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.baiviet')),
                ('ma_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.media')),
            ],
        ),
        migrations.AddField(
            model_name='baiviet',
            name='ma_the',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.the'),
        ),
        migrations.CreateModel(
            name='BaiVietThe',
            fields=[
                ('ma_bv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='csdl.baiviet')),
                ('ma_the', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdl.the')),
            ],
        ),
    ]
