# Generated by Django 5.1.6 on 2025-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('ma_menu', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('trang_thai', models.CharField(choices=[('Dang hoat dong', 'Đang hoạt động'), ('Khong hoat dong', 'Không hoạt động')], default='Dang hoat dong', max_length=20)),
                ('ngay_tao', models.DateField(auto_now_add=True)),
                ('bai_viets', models.ManyToManyField(to='csdl.baiviet')),
            ],
        ),
    ]
