# Generated by Django 5.1.6 on 2025-05-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdl', '0002_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='bai_viets',
        ),
        migrations.AddField(
            model_name='baiviet',
            name='menu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='csdl.menu'),
            preserve_default=False,
        ),
    ]
