# Generated by Django 5.1.6 on 2025-05-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdl', '0003_remove_menu_bai_viets_baiviet_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='menu',
            field=models.ForeignKey(default='Tin tức', on_delete=django.db.models.deletion.CASCADE, to='csdl.menu'),
        ),
    ]
