# Generated by Django 5.1.6 on 2025-05-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdl', '0004_alter_baiviet_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='menu',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='csdl.menu'),
        ),
    ]
